### ISSUE TITLE
Update of indexed container after move (up/down)

### ISSUE THREAD

**Issue by riddy** [SirWayne/ecp-vaadin#8]
There is an issue with the table with the indexed container with moving of elements.

We have 2 elements, AAA and BBB. now we move AAA down.
In the data model  AAA will be removed and inserted after BBB again. In the Indexed Container BBB will be removed and inserted before AAA again. 
The issue the is, that the column-value of the indexed container will be updated only on "addItem"-event, which will be thrown on the wrong item.

We quick fixed this already by changing the "move-down" to a "move-up" by changing the affected elements. 

Problem: This still occours on calling "undo".

Identification: 
In the class `SimplePropertyObservableList` line 182 in the bundle `org.eclipse.core.databinding.property` the `notifyIfChanged`-method does not get the Diff but calculates it, therefore an AAA move-down is changed to BBB move up.

**Comment by SirWayne** [comment]
Fixed with last commit
